config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'library#index'
  resources :books, only: [:show, :index, :edit, :update] do
    resources :collections, only: [:edit, :update, :destroy], module: "books"
  end

  resources :library, only: :index
  resources :logs, only: :index
  resources :halted_files, only: :destroy
  resources :documents, only: :show do
    get :download, on: :member
    post :convert, on: :member
  end
  resources :collections, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch
  attr_accessor :update_from_isbn

  has_and_belongs_to_many :authors
  has_and_belongs_to_many :collections
  has_many :versions, dependent: :destroy
  has_many :pdf_versions, -> { pdf_books }, class_name: "Version"
  has_many :downloadable_versions, -> { downloadable_books }, class_name: "Version"

  scope :with_tag, ->(tag) {
    where("? = ANY(tags)", tag)
  }

  pg_search_scope :search_by_name, against: :name, using: { trigram: { threshold: 0.85 } }
  pg_search_scope :search, against: [
    [:name, 'A'],
    [:tags, 'A'],
    [:description, 'B'],
  ],
  using: { tsearch: { any_word: true, prefix: true } }
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :books, -> { select(:id, :name).order(:created_at) }

  validates :name, presence: true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :version
  has_one :book, through: :version
  has_one_attached :file
end

app/models/import_log.rb
class ImportLog < ApplicationRecord
  scope :with_error, -> { where("data->>'error' IS NOT NULL") }
  scope :halted, -> { where("data->>'halted' IS NOT NULL") }

  def fail?
    data["error"]
  end

  def halted?
    data["halted"]
  end

  def has_file?
    data["file_path"].present? && File.exist?(data["file_path"])
  end

  def remove_file!
    File.unlink(data["file_path"]) if has_file?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, #:registerable,
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  has_many :collections
  enum role: {
    regular: 1,
    admin: 10,
  }
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :book
  has_many :documents, dependent: :destroy
  enum book_type: {
    pdf: 0, epub: 1, mobi: 2, doc: 3, docx: 4, audio: 5,
    azw: 6, fb2: 10, htmlz: 11, lrf: 12, pdb: 13,
    prc: 14, rtf: 15, tpz: 16, txtz: 17, txt: 18,
  }, _suffix: "books"

  scope :downloadable_books, -> { where(book_type: book_types.except(:pdf).values) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/books/collections_controller.rb
module Books
  class CollectionsController < ApplicationController
    before_action :authenticate_user!

    def edit
      authorize Collection

      @book = Book.find(params[:book_id])
      @collections = current_user.collections.order(:name)
    end

    def update
      authorize Collection

      @book = Book.find(params[:book_id])
      @book.update(collection_ids: permitted_collection_ids)
    end

    private

    def permitted_collection_ids
      collection_ids = params
        .require(:book)
        .permit(collection_ids: [])
        .fetch(:collection_ids, [])
        .map(&:to_i)

      current_user.collection_ids & collection_ids
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def index
    @books = Book
      .order(created_at: :desc)
      .page(params[:page]).per(26)
      .includes(:authors)
    @books = @books.with_tag(params[:tag]) if params[:tag].present?
    @books = @books.search(params[:q]) if params[:q].present?
    @books = Decorators::Book::Index.pagination_wrap(@books)
  end

  def show
    @book = Book.find(params[:id])
    @book = Decorators::Book::Show.new(@book)
  end

  def edit
    @book = Book.find(params[:id])
    authorize @book
  end

  def update
    @book = Book.find(params[:id])
    authorize @book

    if @book.update(book_params)
      PipelineUpdateJob.perform_later(@book.id, @book.isbn) if @book.update_from_isbn
      redirect_to @book, notice: "Book will be updated"
    else
      render :edit
    end
  end

  private
    def book_params
      params
        .require(:book)
        .permit(:isbn, :name, :description, :update_from_isbn, tags: [])
        .tap do |prms|
          prms[:tags] = prms[:tags].select(&:present?)
          prms[:update_from_isbn] = string_to_bool(prms[:update_from_isbn])
        end
    end

    def string_to_bool(value)
      ActiveRecord::Type::Boolean.new.cast(value)
    end

    def autofocus_search_input?
      params.except(:controller, :action).empty?
    end
    helper_method :autofocus_search_input?
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @collections = current_user.collections.includes(:books).order(:name)
  end

  def new
    @collection = current_user.collections.new
    authorize @collection
  end

  def create
    @collection = current_user.collections.new(collection_params)
    if @collection.save
      redirect_to collections_path, notice: "Collection was successfully created."
    else
      render :new
    end
  end

  private

    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @books ||= Book.all.includes(:authors)
  end

  def show
    file = document.file

    send_data file.download, type: file.content_type, disposition: :inline
  end

  def download
    file = document.file

    send_data file.download, type: file.content_type,
      disposition: :attachment,
      filename: "#{document.book.name}.#{document.version.book_type}"
  end

  def convert
    authorize document

    PipelineConvertJob.perform_later(document)
    redirect_to document.book, notice: "Conversion enqueued"
  end

  private

  def document
    @document ||= Document.find(params[:id])
  end
end

app/controllers/halted_files_controller.rb
class HaltedFilesController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @log = ImportLog.find(params[:id])
    authorize @log
    @log.remove_file!
  end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def index
    @cluster = ClusterTags.call
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize ImportLog

    @logs = ImportLog.order(created_at: :desc)
    @logs = @logs.with_error if params.key?(:error)
    @logs = @logs.halted if params.key?(:halted)
    @logs = @logs.page(params[:page]).per(50)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOSTRAP_CLASSES = {
    success: "alert-success",
    error: "alert-danger",
    alert: "alert-warning",
    notice: "alert-info"
  }.stringify_keys.freeze

  def bootstrap_class_for(flash_type)
    BOOSTRAP_CLASSES.fetch(flash_type.to_s) { flash_type.to_s }
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat flash_message(msg_type, message)
    end
    nil
  end

  def flash_message(msg_type, message)
    content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show mt-2", role: "alert") do
      concat message
      concat content_tag(:button, close_alert, class: "close", data: { dismiss: 'alert' }, aria: { label: "Close" })
    end
  end

  def close_alert
    content_tag(:span, "&times;".html_safe, aria: { hidden: true })
  end
end

app/views/books/_book.html.erb
<div class="card text-white bg-dark">
  <div class="card-body">
    <h5 class="card-title">
      <%= book.title %>
    </h5>
    <h6 class="card-subtitle">by <%= book.author_names %> - <%= book.isbn %></h6>
    <p class="card-text small" title="<%= book.description %>" ><%= book.summarization %></p>
  </div>
  <div class="card-footer">
    <%= book.tag_badges %>
  </div>
</div>

app/views/books/collections/_form.html.erb
<%= bootstrap_form_with(model: @book, url: book_collection_path(@book.id), method: :patch, remote: true) do |f| %>
  <div>
    <%= f.collection_check_boxes :collection_ids, @collections, :id, :name, hide_label: true %>
  </div>
  <div>
    <%= f.submit class: "btn btn-secondary float-right" %>
  </div>
<% end %>

app/views/books/collections/edit.js.erb
var modal = $('#app-modal')
modal.find('.modal-title').text('Add this book to a collection')
modal.find('.modal-body').html("<%=j render(partial: 'form') %>")
modal.modal('show')

app/views/books/collections/update.js.erb
var modal = $('#app-modal')
modal.modal('hide')

app/views/books/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-10">
    <div class="card text-white bg-dark">
      <div class="card-body">
        <%= form_with model: @book do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, rows: 5, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :isbn, "ISBN" %>
            <%= f.text_field :isbn, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :tags %>
            <%= f.select :tags, @book.tags, {}, { class: "form-control select2-tags-input", multiple: true } %>
          </div>

         <div class="form-group">
            <div class="form-check">
              <%= f.check_box :update_from_isbn, class: "form-check-input" %>
              <%= f.label :update_from_isbn, "Update from ISBN", class: "form-check-label" %>
            </div>
          </div>

          <%= f.submit "Update", class: "btn btn-secondary float-right" %>
        <% end %>
      </div>
      <div class="card-footer">
        <%= link_to "Cancel", @book, class: "text-white" %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="row justify-content-center">
  <div class="col-8">
      <%= form_with url: books_path, method: :get, local: true do |f| %>
       <div class="form-group mt-3">
        <%= f.search_field :q, value: params[:q], class: "form-control form-control-lg", placeholder: "Search", autofocus: autofocus_search_input?, aria: { label: "Search" } %>
        <%= f.submit "Search", class: "d-none" %>
        </div>
      <% end %>
  </div>
</div>

<% if @books.any? %>
  <% @books.each_slice(2) do |books| %>
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="card-deck mt-3">
          <%= render partial: "book", collection: books, as: :book %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= paginate @books %>
    </div>
  </div>
<% else %>
  <div class="row justify-content-center">
    <div class="col-10">
      <p class="placeholder">There are no books yet.</p>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="mt-3">
      <div class="card text-white bg-dark">
        <div class="card-body">
          <h5 class="card-title">
            <span>
              <%= @book.title %>
            </span>
            <span class="float-right">
              <% if policy(Collection).edit? %>
                <%= link_to octicon("repo-clone", fill: "currentcolor"),
                edit_book_collection_path(@book),
                remote: true, class: "btn btn-secondary" %>
              <% end %>

              <% if policy(@book).edit? %>
                <%= link_to octicon("pencil", fill: "currentcolor"),
                  edit_book_path(@book), class: "ml-3 btn btn-secondary" %>
              <% end %>
            </span>
          </h5>

          <h6 class="card-subtitle">by <%= @book.author_names %> - <%= @book.isbn %></h6>
          <h6 class="card-subtitle mt-2">
            <%= @book.link_to_pdf_versions %>
            <%= @book.link_to_downloadable_versions %>
          </h6>
          <p class="card-text small"><%= @book.summarization %></p>
        </div>
        <div class="card-footer">
          <%= @book.tag_badges %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/collections/_collection.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h5 class="card-title">
          <%= collection.name %>
        </h5>
        <ul class="list-group list-group-flush">
          <% if collection.books.any? %>
            <% collection.books.each do |book| %>
              <li class="list-group-item bg-dark">
                <%= link_to(book.name, book_path(book), class: "text-white") %>
              </li>
            <% end %>
          <% else %>
            <li class="list-group-item bg-dark">No books here.</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h4 class="card-title mr-auto d-inline-block mb-0">
          <%= pluralize(@collections.flat_map(&:books).size, "book") %>
          across
          <%= pluralize(@collections.size, "collection") %>
        </h4>
        <span class="float-right">
          <%= link_to new_collection_path, class: "text-white" do %>
            <%= octicon(:plus, height: 24, fill: "currentcolor") %>
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

<%= render @collections %>

app/views/collections/new.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mt-3">
      <div class="card-body">
        <h5 class="card-title">
          Create Collection
        </h5>
        <%= form_with(model: @collection, local: true) do |form| %>
          <% if @collection.errors.any? %>
            <div class="alert alert-danger">
              <p><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</p>

              <ul>
              <% @collection.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.submit class: "btn btn-secondary float-right" %>
          </div>
        <% end %>
      </div>
      <div class="card-footer">
        <%= link_to 'Back', collections_path, class: "text-white" %>
      </div>
    </div>
  </div>
</div>

app/views/halted_files/destroy.js.erb
var elementId = '<%= j "halted-button-#{@log.id}" %>'
var element = document.getElementById(elementId)
element.parentNode.removeChild(element)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark box-shadow">
        <%= link_to root_path, class: "navbar-brand mr-2" do %>
          <%= octicon(:book, height: 32, fill: "currentcolor") %>
          <strong>Bookshelf</strong>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggler">
          <%= render_navigation expand_all: true, context: "navigation/application" %>
          <%= render_navigation expand_all: true, context: "navigation/user" %>
        </div>
      </nav>
    </header>
    <div class="container-fluid mb-5">
      <%= flash_messages %>
      <%= yield %>
      <div class="modal fade" id="app-modal" tabindex="-1" role="dialog" aria-labelledby="modal-title-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content text-white bg-dark">
            <div class="modal-header">
              <h5 class="modal-title" id="modal-title-label"></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/library/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-10">
    <% ClusterTags.each_category do |category| %>
      <div class="mt-2 text-justify">
        <% @cluster[category].to_a.each do |tag| %>
          <%= link_to(books_path(tag: tag["word"])) do %>
            <%= content_tag(:span, class: "badge badge-secondary mt-2 tag-#{category}") do %>
              <%= tag["word"] %>
              <%= content_tag(:span, tag["frequency"], class: "badge badge-light") %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/logs/_log.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <div class="card text-white bg-dark mb-2">
      <div class="card-header" id="heading-<%= log.id %>">
        <h5 class="mb-0">
          <button class="btn btn-link text-white" data-toggle="collapse" data-target="#collapse-<%= log.id %>" aria-expanded="false" aria-controls="collapse-<%= log.id %>">
            <span>#<%= log.id %>.</span>
            <%= log.created_at %>
            <%= octicon("alert", class: "ml-2", fill: "currentcolor") if log.fail? %>
            <%= octicon("stop", class: "ml-2", fill: "currentcolor") if log.halted? %>
          </button>
        </h5>
      </div>

      <div id="collapse-<%= log.id %>" class="collapse" aria-labelledby="heading-<%= log.id %>" data-parent="#accordion">
        <div class="card-body">
          <pre class="text-white"><%= JSON.pretty_generate(log.data) %></pre>
        </div>
        <div class="card-footer">
          <%= content_tag(:div, id: "halted-button-#{log.id}") do %>
            <% if policy(log).destroy? && log.halted? && log.has_file? %>
              <%= link_to octicon("x", fill: "currentcolor"), halted_file_path(log), method: :delete, data: { confirm: "Are you sure?" }, title: "Remove file", remote: true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/logs/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-10">
    <nav>
      <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
        <%= link_to "All", logs_path, class: "nav-item nav-link #{'active' if params.slice(:error, :halted).empty?}", role: "tab", aria: { selected: params.empty? } %>
        <%= link_to "Errors", logs_path(error: ""), class: "nav-item nav-link #{'active' if params.key?(:error)}", role: "tab", aria: { selected: params.key?(:error) } %>
        <%= link_to "Halted", logs_path(halted: ""), class: "nav-item nav-link #{'active' if params.key?(:halted)}", role: "tab", aria: { selected: params.key?(:halted) } %>
      </div>
    </nav>
  </div>
</div>

<div id="accordion" class="mt-3">
  <%= render partial: "log", collection: @logs, as: :log %>
</div>

<div class="row justify-content-center">
  <div class="col-10">
    <%= paginate @logs %>
  </div>
</div>